use crate::parser::{ArgType, FdSpec, InboundKind, Message, NamedEnum, NamedStruct, Protocol};
use std::fmt::Write;

// ---------------------------------------------------------------------------
// Public entry points

pub fn emit_header(p: &Protocol) -> String {
    let inbound = MsgKind::inbound_for(p.inbound_kind);
    let mut out = String::new();
    emit_header_prologue(&mut out, p);
    emit_common_types(&mut out);
    emit_named_types(&mut out, &p.enums, &p.structs);
    emit_named_free_decls(&mut out, &p.structs);
    emit_opcodes(&mut out, p, inbound);
    for m in &p.requests {
        emit_message_struct(&mut out, m, inbound);
    }
    for m in &p.events {
        emit_message_struct(&mut out, m, MsgKind::Event);
    }
    emit_function_decls(&mut out, p, inbound);
    emit_header_epilogue(&mut out);
    out
}

fn emit_named_free_decls(out: &mut String, structs: &[NamedStruct]) {
    if structs.is_empty() {
        return;
    }
    writeln!(out, "/* --- Named value lifecycle --- */").unwrap();
    writeln!(out).unwrap();
    for item in structs {
        let type_name = named_c_type(&item.name);
        writeln!(
            out,
            "void waywallen_{}_free({type_name} *value);",
            item.name
        )
        .unwrap();
    }
    writeln!(out).unwrap();
}

pub fn emit_types_header(p: &Protocol) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */"
    )
    .unwrap();
    writeln!(out, "#ifndef WAYWALLEN_DISPLAY_PROTOCOL_TYPES_H").unwrap();
    writeln!(out, "#define WAYWALLEN_DISPLAY_PROTOCOL_TYPES_H").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#include <stdbool.h>").unwrap();
    writeln!(out, "#include <stddef.h>").unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out).unwrap();
    emit_value_types(&mut out);
    emit_named_types(&mut out, &p.enums, &p.structs);
    writeln!(out, "#endif /* WAYWALLEN_DISPLAY_PROTOCOL_TYPES_H */").unwrap();
    out
}

// ---------------------------------------------------------------------------
// Header

#[derive(Copy, Clone, PartialEq, Eq)]
enum MsgKind {
    Request,
    EventIn,
    Event,
}

impl MsgKind {
    fn inbound_for(k: InboundKind) -> Self {
        match k {
            InboundKind::Request => Self::Request,
            InboundKind::EventIn => Self::EventIn,
        }
    }
    fn prefix(self) -> &'static str {
        match self {
            Self::Request => "ww_req_",
            Self::EventIn => "ww_evt_in_",
            Self::Event => "ww_evt_",
        }
    }
    fn enum_prefix(self) -> &'static str {
        match self {
            Self::Request => "WW_REQ_",
            Self::EventIn => "WW_EVT_IN_",
            Self::Event => "WW_EVT_",
        }
    }
    fn enum_typedef(self) -> (&'static str, &'static str) {
        match self {
            Self::Request => ("ww_request_op", "ww_request_op_t"),
            Self::EventIn => ("ww_event_in_op", "ww_event_in_op_t"),
            Self::Event => ("ww_event_op", "ww_event_op_t"),
        }
    }
}

fn emit_header_prologue(out: &mut String, p: &Protocol) {
    writeln!(
        out,
        "/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */"
    )
    .unwrap();
    writeln!(out, "/* Source: protocol/{}_v{}.xml */", p.name, p.version).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifndef WAYWALLEN_PROTO_H").unwrap();
    writeln!(out, "#define WAYWALLEN_PROTO_H").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#include <stdint.h>").unwrap();
    writeln!(out, "#include <stddef.h>").unwrap();
    writeln!(out, "#include <stdbool.h>").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "extern \"C\" {{").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "#define WW_PROTOCOL_NAME    \"{}-v{}\"",
        p.name.replace('_', "-"),
        p.version
    )
    .unwrap();
    writeln!(out, "#define WW_PROTOCOL_VERSION {}", p.version).unwrap();
    writeln!(out).unwrap();
}

fn emit_header_epilogue(out: &mut String) {
    writeln!(out).unwrap();
    writeln!(out, "#ifdef __cplusplus").unwrap();
    writeln!(out, "}} /* extern \"C\" */").unwrap();
    writeln!(out, "#endif").unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#endif /* WAYWALLEN_PROTO_H */").unwrap();
}

fn emit_common_types(out: &mut String) {
    emit_value_types(out);
    out.push_str(
        r#"/* --- Codec buffer + return codes --- */

typedef struct ww_buf {
    uint8_t *data;
    size_t len;
    size_t cap;
} ww_buf_t;

/* Return codes: 0 = success, negative = -errno-ish. */
#define WW_OK                  0
#define WW_ERR_SHORT           (-1)   /* buffer truncated */
#define WW_ERR_BAD_STRING      (-2)   /* malformed length-prefixed string */
#define WW_ERR_BAD_ARRAY       (-3)   /* array length overflow */
#define WW_ERR_TRAILING        (-4)   /* unexpected trailing bytes */
#define WW_ERR_UNKNOWN_OPCODE  (-5)
#define WW_ERR_NOMEM           (-6)
#define WW_ERR_OVERFLOW        (-7)   /* frame bigger than u16 can address */
#define WW_ERR_BAD_BOOL        (-8)   /* boolean is not canonical 0/1 */
#define WW_ERR_BAD_ENUM        (-9)   /* enum value is not declared */

"#,
    );
}

fn emit_value_types(out: &mut String) {
    out.push_str(
        r#"#ifndef WAYWALLEN_PROTOCOL_VALUE_TYPES_DEFINED
#define WAYWALLEN_PROTOCOL_VALUE_TYPES_DEFINED

/* --- Shared primitive value types --- */

typedef struct ww_rect {
    float x;
    float y;
    float w;
    float h;
} ww_rect_t;

typedef struct ww_array_u32 {
    uint32_t count;
    uint32_t *data;    /* heap-allocated by decoder; NULL if count==0 */
} ww_array_u32_t;

typedef struct ww_array_u64 {
    uint32_t count;
    uint64_t *data;
} ww_array_u64_t;

typedef struct ww_array_i32 {
    uint32_t count;
    int32_t *data;
} ww_array_i32_t;

typedef struct ww_array_i64 {
    uint32_t count;
    int64_t *data;
} ww_array_i64_t;

typedef struct ww_array_f32 {
    uint32_t count;
    float *data;
} ww_array_f32_t;

typedef struct ww_array_f64 {
    uint32_t count;
    double *data;
} ww_array_f64_t;

typedef struct ww_array_string {
    uint32_t count;
    char **data;       /* each entry NUL-terminated, heap-allocated */
} ww_array_string_t;

typedef struct ww_kv {
    char *key;
    char *value;
} ww_kv_t;

typedef struct ww_kv_list {
    uint32_t count;
    ww_kv_t *data;
} ww_kv_list_t;

#endif /* WAYWALLEN_PROTOCOL_VALUE_TYPES_DEFINED */

"#,
    );
}

fn emit_named_types(out: &mut String, enums: &[NamedEnum], structs: &[NamedStruct]) {
    if enums.is_empty() && structs.is_empty() {
        return;
    }
    writeln!(out, "#ifndef WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED").unwrap();
    writeln!(out, "#define WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED").unwrap();
    writeln!(out).unwrap();
    for item in enums {
        let type_name = named_c_type(&item.name);
        writeln!(out, "typedef enum {} {{", type_name.trim_end_matches("_t")).unwrap();
        for entry in &item.entries {
            writeln!(
                out,
                "    WAYWALLEN_{}_{} = {},",
                item.name.to_uppercase(),
                entry.name.to_uppercase(),
                entry.value
            )
            .unwrap();
        }
        writeln!(out, "}} {type_name};").unwrap();
        writeln!(out).unwrap();
    }
    for item in structs {
        let type_name = named_c_type(&item.name);
        writeln!(
            out,
            "typedef struct {} {{",
            type_name.trim_end_matches("_t")
        )
        .unwrap();
        for field in &item.fields {
            writeln!(
                out,
                "    {} {};",
                c_type(&field.ty),
                c_field_name(&field.name)
            )
            .unwrap();
        }
        writeln!(out, "}} {type_name};").unwrap();
        writeln!(out).unwrap();
    }
    writeln!(out, "#endif /* WAYWALLEN_PROTOCOL_NAMED_TYPES_DEFINED */").unwrap();
    writeln!(out).unwrap();
}

fn emit_opcodes(out: &mut String, p: &Protocol, inbound: MsgKind) {
    writeln!(out, "/* --- Opcodes --- */").unwrap();
    writeln!(out).unwrap();
    let (in_tag, in_typedef) = inbound.enum_typedef();
    writeln!(out, "typedef enum {in_tag} {{").unwrap();
    for m in &p.requests {
        writeln!(
            out,
            "    {}{} = {},",
            inbound.enum_prefix(),
            m.name.to_uppercase(),
            m.opcode
        )
        .unwrap();
    }
    writeln!(out, "}} {in_typedef};").unwrap();
    writeln!(out).unwrap();
    let (out_tag, out_typedef) = MsgKind::Event.enum_typedef();
    writeln!(out, "typedef enum {out_tag} {{").unwrap();
    for m in &p.events {
        writeln!(
            out,
            "    {}{} = {},",
            MsgKind::Event.enum_prefix(),
            m.name.to_uppercase(),
            m.opcode
        )
        .unwrap();
    }
    writeln!(out, "}} {out_typedef};").unwrap();
    writeln!(out).unwrap();
}

fn emit_message_struct(out: &mut String, m: &Message, kind: MsgKind) {
    let type_name = message_type_name(m, kind);
    writeln!(out, "typedef struct {} {{", type_name).unwrap();
    if m.args.is_empty() {
        writeln!(out, "    int _empty; /* C forbids empty structs */").unwrap();
    } else {
        for a in &m.args {
            let ty = c_type(&a.ty);
            let field = c_field_name(&a.name);
            // Pointer types render `char *name;` (star glued to name);
            // everything else renders `uint32_t name;`.
            if ty.ends_with('*') {
                writeln!(out, "    {ty}{field};").unwrap();
            } else {
                writeln!(out, "    {ty} {field};").unwrap();
            }
        }
    }
    writeln!(out, "}} {};", type_name).unwrap();
    writeln!(out).unwrap();
}

fn emit_function_decls(out: &mut String, p: &Protocol, inbound: MsgKind) {
    writeln!(out, "/* --- Per-message functions ---").unwrap();
    writeln!(
        out,
        " * encode:        append wire body to `out` (header is the caller's job)"
    )
    .unwrap();
    writeln!(
        out,
        " * decode:        consume `len` bytes; on success owns heap allocations"
    )
    .unwrap();
    writeln!(
        out,
        " * free:          release any heap fields the decoder populated"
    )
    .unwrap();
    writeln!(
        out,
        " * expected_fds:  how many SCM_RIGHTS fds the wire frame must carry"
    )
    .unwrap();
    writeln!(out, " */").unwrap();
    writeln!(out).unwrap();

    for m in &p.requests {
        emit_message_decls(out, m, inbound);
    }
    for m in &p.events {
        emit_message_decls(out, m, MsgKind::Event);
    }

    // ww_buf helpers.
    writeln!(out, "/* --- Output buffer helpers --- */").unwrap();
    writeln!(out, "void ww_buf_init(ww_buf_t *b);").unwrap();
    writeln!(out, "void ww_buf_free(ww_buf_t *b);").unwrap();
    writeln!(out, "int  ww_buf_reserve(ww_buf_t *b, size_t additional);").unwrap();
    writeln!(out).unwrap();
}

fn emit_message_decls(out: &mut String, m: &Message, kind: MsgKind) {
    let type_name = message_type_name(m, kind);
    let fn_prefix = type_name.trim_end_matches("_t");
    writeln!(
        out,
        "int  {fn_prefix}_encode(const {type_name} *m, ww_buf_t *out);"
    )
    .unwrap();
    writeln!(
        out,
        "int  {fn_prefix}_decode(const uint8_t *buf, size_t len, {type_name} *out);"
    )
    .unwrap();
    writeln!(out, "void {fn_prefix}_free({type_name} *m);").unwrap();
    let fd_signature = match &m.fds {
        FdSpec::None | FdSpec::Fixed(_) => {
            format!("uint32_t {fn_prefix}_expected_fds(const {type_name} *m);")
        }
        FdSpec::Product(_) => {
            format!("uint32_t {fn_prefix}_expected_fds(const {type_name} *m);")
        }
    };
    writeln!(out, "{fd_signature}").unwrap();
    writeln!(out).unwrap();
}

// ---------------------------------------------------------------------------
// Source (.c)

pub fn emit_source(p: &Protocol) -> String {
    emit_source_with_include(p, default_c_include(&p.name))
}

/// Default `#include "..."` path for generated C source.
/// Different protocol consumers install headers at different paths.
pub fn default_c_include(protocol_name: &str) -> &'static str {
    match protocol_name {
        "waywallen-ipc" | "waywallen_ipc" => "waywallen-bridge/ipc_v3.h",
        _ => "ww_proto.h",
    }
}

pub fn emit_source_with_include(p: &Protocol, include: &str) -> String {
    let mut out = String::new();
    writeln!(
        out,
        "/* AUTO-GENERATED by wayproto-gen. DO NOT EDIT BY HAND. */"
    )
    .unwrap();
    writeln!(out, "/* Source: protocol/{}_v{}.xml */", p.name, p.version).unwrap();
    writeln!(out).unwrap();
    writeln!(out, "#include \"{include}\"").unwrap();
    writeln!(out).unwrap();
    out.push_str(
        r#"#include <stdint.h>
#include <stdlib.h>
#include <string.h>

/* Some wire helpers are unused for the current protocol revision (e.g.
 * no i64 args today) but we emit them unconditionally so future
 * revisions can add those types without touching the codegen.
 *
 * -Wtype-limits is silenced for the same reason: array-length overflow
 * guards compare `uint32_t > SIZE_MAX/sizeof(T)`, which on 64-bit
 * platforms is trivially false (the check still fires on 32-bit where
 * it can actually overflow). */
#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic push
#  pragma GCC diagnostic ignored "-Wunused-function"
#  pragma GCC diagnostic ignored "-Wtype-limits"
#endif

/* ======================================================================
 * Output buffer helpers
 * ====================================================================== */

void ww_buf_init(ww_buf_t *b) {
    b->data = NULL;
    b->len = 0;
    b->cap = 0;
}

void ww_buf_free(ww_buf_t *b) {
    free(b->data);
    b->data = NULL;
    b->len = 0;
    b->cap = 0;
}

int ww_buf_reserve(ww_buf_t *b, size_t additional) {
    size_t need;
    if (additional > SIZE_MAX - b->len) return WW_ERR_OVERFLOW;
    need = b->len + additional;
    if (need > b->cap) {
        size_t new_cap = b->cap ? b->cap : 64;
        while (new_cap < need) {
            if (new_cap > SIZE_MAX / 2) return WW_ERR_OVERFLOW;
            new_cap *= 2;
        }
        uint8_t *nd = (uint8_t *)realloc(b->data, new_cap);
        if (!nd) return WW_ERR_NOMEM;
        b->data = nd;
        b->cap = new_cap;
    }
    return WW_OK;
}

/* ======================================================================
 * Writer helpers
 * ====================================================================== */

static int w_bytes(ww_buf_t *b, const void *src, size_t n) {
    int rc = ww_buf_reserve(b, n);
    if (rc) return rc;
    if (n > b->cap - b->len) return WW_ERR_OVERFLOW;
    memcpy(b->data + b->len, src, n);
    b->len += n;
    return WW_OK;
}

static int w_u32(ww_buf_t *b, uint32_t v) {
    uint8_t out[4];
    out[0] = (uint8_t)(v);
    out[1] = (uint8_t)(v >> 8);
    out[2] = (uint8_t)(v >> 16);
    out[3] = (uint8_t)(v >> 24);
    return w_bytes(b, out, 4);
}
static int w_bool(ww_buf_t *b, bool v) { return w_u32(b, v ? 1u : 0u); }
static int w_i32(ww_buf_t *b, int32_t v) { return w_u32(b, (uint32_t)v); }

static int w_u64(ww_buf_t *b, uint64_t v) {
    uint8_t out[8];
    out[0] = (uint8_t)(v);
    out[1] = (uint8_t)(v >> 8);
    out[2] = (uint8_t)(v >> 16);
    out[3] = (uint8_t)(v >> 24);
    out[4] = (uint8_t)(v >> 32);
    out[5] = (uint8_t)(v >> 40);
    out[6] = (uint8_t)(v >> 48);
    out[7] = (uint8_t)(v >> 56);
    return w_bytes(b, out, 8);
}
static int w_i64(ww_buf_t *b, int64_t v) { return w_u64(b, (uint64_t)v); }

static int w_f32(ww_buf_t *b, float v) {
    uint32_t bits;
    memcpy(&bits, &v, 4);
    return w_u32(b, bits);
}
static int w_f64(ww_buf_t *b, double v) {
    uint64_t bits;
    memcpy(&bits, &v, 8);
    return w_u64(b, bits);
}

static int w_pad4(ww_buf_t *b) {
    static const uint8_t zeros[3] = {0, 0, 0};
    size_t pad = (4 - (b->len & 3)) & 3;
    if (pad == 0) return WW_OK;
    return w_bytes(b, zeros, pad);
}

static int w_string(ww_buf_t *b, const char *s) {
    size_t n = s ? strlen(s) : 0;
    if (n > 0xfffffffeULL) return WW_ERR_OVERFLOW;
    uint32_t len = (uint32_t)(n + 1);  /* includes NUL */
    int rc = w_u32(b, len);
    if (rc) return rc;
    rc = w_bytes(b, s ? s : "", n);
    if (rc) return rc;
    static const uint8_t nul = 0;
    rc = w_bytes(b, &nul, 1);
    if (rc) return rc;
    return w_pad4(b);
}

static int w_rect(ww_buf_t *b, const ww_rect_t *r) {
    int rc;
    if ((rc = w_f32(b, r->x))) return rc;
    if ((rc = w_f32(b, r->y))) return rc;
    if ((rc = w_f32(b, r->w))) return rc;
    if ((rc = w_f32(b, r->h))) return rc;
    return WW_OK;
}

static int w_array_u32(ww_buf_t *b, const ww_array_u32_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_u32(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_i32(ww_buf_t *b, const ww_array_i32_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_i32(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_u64(ww_buf_t *b, const ww_array_u64_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_u64(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_i64(ww_buf_t *b, const ww_array_i64_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_i64(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_f32(ww_buf_t *b, const ww_array_f32_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_f32(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_f64(ww_buf_t *b, const ww_array_f64_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_f64(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_array_string(ww_buf_t *b, const ww_array_string_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_string(b, a->data[i]);
        if (rc) return rc;
    }
    return WW_OK;
}
static int w_kv_list(ww_buf_t *b, const ww_kv_list_t *a) {
    int rc = w_u32(b, a->count);
    if (rc) return rc;
    for (uint32_t i = 0; i < a->count; i++) {
        rc = w_string(b, a->data[i].key);
        if (rc) return rc;
        rc = w_string(b, a->data[i].value);
        if (rc) return rc;
    }
    return WW_OK;
}

/* ======================================================================
 * Reader helpers
 * ====================================================================== */

typedef struct {
    const uint8_t *buf;
    size_t pos;
    size_t len;
} ww_rd_t;

static int rd_need(const ww_rd_t *r, size_t n) {
    return (r->len - r->pos >= n) ? WW_OK : WW_ERR_SHORT;
}

static int rd_u32(ww_rd_t *r, uint32_t *out) {
    int rc = rd_need(r, 4);
    if (rc) return rc;
    const uint8_t *p = r->buf + r->pos;
    *out = (uint32_t)p[0] | ((uint32_t)p[1] << 8)
        | ((uint32_t)p[2] << 16) | ((uint32_t)p[3] << 24);
    r->pos += 4;
    return WW_OK;
}
static int rd_bool(ww_rd_t *r, bool *out) {
    uint32_t v;
    int rc = rd_u32(r, &v);
    if (rc) return rc;
    if (v > 1u) return WW_ERR_BAD_BOOL;
    *out = v != 0u;
    return WW_OK;
}
static int rd_i32(ww_rd_t *r, int32_t *out) {
    uint32_t v; int rc = rd_u32(r, &v); *out = (int32_t)v; return rc;
}
static int rd_u64(ww_rd_t *r, uint64_t *out) {
    int rc = rd_need(r, 8);
    if (rc) return rc;
    const uint8_t *p = r->buf + r->pos;
    *out = (uint64_t)p[0] | ((uint64_t)p[1] << 8)
        | ((uint64_t)p[2] << 16) | ((uint64_t)p[3] << 24)
        | ((uint64_t)p[4] << 32) | ((uint64_t)p[5] << 40)
        | ((uint64_t)p[6] << 48) | ((uint64_t)p[7] << 56);
    r->pos += 8;
    return WW_OK;
}
static int rd_i64(ww_rd_t *r, int64_t *out) {
    uint64_t v; int rc = rd_u64(r, &v); *out = (int64_t)v; return rc;
}
static int rd_f32(ww_rd_t *r, float *out) {
    uint32_t bits; int rc = rd_u32(r, &bits); if (rc) return rc;
    memcpy(out, &bits, 4);
    return WW_OK;
}
static int rd_f64(ww_rd_t *r, double *out) {
    uint64_t bits; int rc = rd_u64(r, &bits); if (rc) return rc;
    memcpy(out, &bits, 8);
    return WW_OK;
}

static int rd_rect(ww_rd_t *r, ww_rect_t *out) {
    int rc;
    if ((rc = rd_f32(r, &out->x))) return rc;
    if ((rc = rd_f32(r, &out->y))) return rc;
    if ((rc = rd_f32(r, &out->w))) return rc;
    if ((rc = rd_f32(r, &out->h))) return rc;
    return WW_OK;
}

static int rd_string(ww_rd_t *r, char **out) {
    uint32_t len;
    int rc = rd_u32(r, &len);
    if (rc) return rc;
    if (len == 0) return WW_ERR_BAD_STRING;  /* includes NUL */
    size_t padded = ((size_t)len + 3u) & ~(size_t)3u;
    if (padded < (size_t)len) return WW_ERR_OVERFLOW;
    rc = rd_need(r, padded);
    if (rc) return rc;
    if (r->buf[r->pos + len - 1] != 0) return WW_ERR_BAD_STRING;
    char *s = (char *)malloc(len);
    if (!s) return WW_ERR_NOMEM;
    memcpy(s, r->buf + r->pos, len);
    *out = s;
    r->pos += padded;
    return WW_OK;
}

/* Guard against an untrusted count forcing a huge allocation (DoS). */
#define DEFINE_ARRAY_READER(NAME, CTYPE, READ_ONE)                     \
    static int rd_array_##NAME(ww_rd_t *r, ww_array_##NAME##_t *out) { \
        uint32_t n;                                                    \
        int rc = rd_u32(r, &n);                                        \
        if (rc) return rc;                                             \
        out->count = 0;                                                \
        out->data = NULL;                                              \
        if (n == 0) return WW_OK;                                      \
        if ((size_t)n > r->len - r->pos) return WW_ERR_BAD_ARRAY;      \
        if ((size_t)n > (SIZE_MAX / sizeof(CTYPE))) return WW_ERR_BAD_ARRAY; \
        CTYPE *arr = (CTYPE *)malloc((size_t)n * sizeof(CTYPE));       \
        if (!arr) return WW_ERR_NOMEM;                                 \
        for (uint32_t i = 0; i < n; i++) {                             \
            rc = READ_ONE(r, &arr[i]);                                 \
            if (rc) { free(arr); return rc; }                          \
        }                                                              \
        out->count = n;                                                \
        out->data = arr;                                               \
        return WW_OK;                                                  \
    }

DEFINE_ARRAY_READER(u32, uint32_t, rd_u32)
DEFINE_ARRAY_READER(i32, int32_t,  rd_i32)
DEFINE_ARRAY_READER(u64, uint64_t, rd_u64)
DEFINE_ARRAY_READER(i64, int64_t,  rd_i64)
DEFINE_ARRAY_READER(f32, float,    rd_f32)
DEFINE_ARRAY_READER(f64, double,   rd_f64)

static int rd_array_string(ww_rd_t *r, ww_array_string_t *out) {
    uint32_t n;
    int rc = rd_u32(r, &n);
    if (rc) return rc;
    out->count = 0;
    out->data = NULL;
    if (n == 0) return WW_OK;
    if ((size_t)n > r->len - r->pos) return WW_ERR_BAD_ARRAY;
    if ((size_t)n > (SIZE_MAX / sizeof(char *))) return WW_ERR_BAD_ARRAY;
    char **arr = (char **)calloc(n, sizeof(char *));
    if (!arr) return WW_ERR_NOMEM;
    for (uint32_t i = 0; i < n; i++) {
        rc = rd_string(r, &arr[i]);
        if (rc) {
            for (uint32_t j = 0; j < i; j++) free(arr[j]);
            free(arr);
            return rc;
        }
    }
    out->count = n;
    out->data = arr;
    return WW_OK;
}

static int rd_kv_list(ww_rd_t *r, ww_kv_list_t *out) {
    uint32_t n;
    int rc = rd_u32(r, &n);
    if (rc) return rc;
    out->count = 0;
    out->data = NULL;
    if (n == 0) return WW_OK;
    if ((size_t)n > r->len - r->pos) return WW_ERR_BAD_ARRAY;
    if ((size_t)n > (SIZE_MAX / sizeof(ww_kv_t))) return WW_ERR_BAD_ARRAY;
    ww_kv_t *arr = (ww_kv_t *)calloc(n, sizeof(ww_kv_t));
    if (!arr) return WW_ERR_NOMEM;
    for (uint32_t i = 0; i < n; i++) {
        rc = rd_string(r, &arr[i].key);
        if (!rc) rc = rd_string(r, &arr[i].value);
        if (rc) {
            for (uint32_t j = 0; j <= i; j++) {
                free(arr[j].key);
                free(arr[j].value);
            }
            free(arr);
            return rc;
        }
    }
    out->count = n;
    out->data = arr;
    return WW_OK;
}

static void free_array_string(ww_array_string_t *a) {
    if (!a->data) { a->count = 0; return; }
    for (uint32_t i = 0; i < a->count; i++) free(a->data[i]);
    free(a->data);
    a->data = NULL;
    a->count = 0;
}
static void free_kv_list(ww_kv_list_t *a) {
    if (!a->data) { a->count = 0; return; }
    for (uint32_t i = 0; i < a->count; i++) {
        free(a->data[i].key);
        free(a->data[i].value);
    }
    free(a->data);
    a->data = NULL;
    a->count = 0;
}

#if defined(__GNUC__) || defined(__clang__)
#  pragma GCC diagnostic pop
#endif

/* ======================================================================
 * Per-message implementations
 * ====================================================================== */

"#,
    );

    emit_named_enum_helpers(&mut out, &p.enums);
    emit_named_helpers(&mut out, &p.structs);

    let inbound = MsgKind::inbound_for(p.inbound_kind);
    for m in &p.requests {
        emit_message_impl(&mut out, m, inbound);
    }
    for m in &p.events {
        emit_message_impl(&mut out, m, MsgKind::Event);
    }

    out
}

fn emit_named_enum_helpers(out: &mut String, enums: &[NamedEnum]) {
    for item in enums {
        let c_name = named_c_type(&item.name);
        writeln!(
            out,
            "static int w_{}(ww_buf_t *b, {c_name} v) {{",
            item.name
        )
        .unwrap();
        writeln!(out, "    return w_u32(b, (uint32_t)v);").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "static int rd_{}(ww_rd_t *r, {c_name} *out) {{",
            item.name
        )
        .unwrap();
        writeln!(out, "    uint32_t value;").unwrap();
        writeln!(out, "    int rc = rd_u32(r, &value);").unwrap();
        writeln!(out, "    if (rc) return rc;").unwrap();
        writeln!(out, "    switch (value) {{").unwrap();
        for entry in &item.entries {
            writeln!(
                out,
                "    case {}: *out = WAYWALLEN_{}_{}; return WW_OK;",
                entry.value,
                item.name.to_uppercase(),
                entry.name.to_uppercase()
            )
            .unwrap();
        }
        writeln!(out, "    default: return WW_ERR_BAD_ENUM;").unwrap();
        writeln!(out, "    }}").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

fn emit_named_helpers(out: &mut String, structs: &[NamedStruct]) {
    for item in structs {
        let c_name = named_c_type(&item.name);
        writeln!(
            out,
            "static int w_{}(ww_buf_t *b, const {c_name} *v) {{",
            item.name
        )
        .unwrap();
        writeln!(out, "    int rc;").unwrap();
        for field in &item.fields {
            let name = c_field_name(&field.name);
            let call = encode_call_for(&field.ty, &name);
            let arg = match field.ty {
                ArgType::Bool
                | ArgType::U32
                | ArgType::I32
                | ArgType::U64
                | ArgType::I64
                | ArgType::F32
                | ArgType::F64
                | ArgType::Enum(_) => format!("v->{name}"),
                ArgType::String => format!("v->{name}"),
                ArgType::Rect | ArgType::KvList | ArgType::Array(_) | ArgType::Named(_) => {
                    format!("&v->{name}")
                }
            };
            writeln!(out, "    if ((rc = {call}(b, {arg}))) return rc;").unwrap();
        }
        writeln!(out, "    return WW_OK;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(
            out,
            "static int rd_{}(ww_rd_t *r, {c_name} *v) {{",
            item.name
        )
        .unwrap();
        writeln!(out, "    int rc;").unwrap();
        for field in &item.fields {
            let name = c_field_name(&field.name);
            let call = decode_call_for(&field.ty);
            writeln!(out, "    if ((rc = {call}(r, &v->{name}))) return rc;").unwrap();
        }
        writeln!(out, "    return WW_OK;").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "static void free_{}({c_name} *v) {{", item.name).unwrap();
        let owned: Vec<_> = item
            .fields
            .iter()
            .filter(|field| ty_owns_heap(&field.ty))
            .collect();
        if owned.is_empty() {
            writeln!(out, "    (void)v;").unwrap();
        } else {
            for field in owned {
                let name = c_field_name(&field.name);
                writeln!(out, "    {}", free_stmt_for_base(&field.ty, "v", &name)).unwrap();
            }
        }
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();

        writeln!(out, "void waywallen_{}_free({c_name} *value) {{", item.name).unwrap();
        writeln!(out, "    if (!value) return;").unwrap();
        writeln!(out, "    free_{}(value);", item.name).unwrap();
        writeln!(out, "    memset(value, 0, sizeof(*value));").unwrap();
        writeln!(out, "}}").unwrap();
        writeln!(out).unwrap();
    }
}

fn emit_message_impl(out: &mut String, m: &Message, kind: MsgKind) {
    let type_name = message_type_name(m, kind);
    let fn_prefix = type_name.trim_end_matches("_t").to_string();

    // ---- encode ----
    writeln!(
        out,
        "int {fn_prefix}_encode(const {type_name} *m, ww_buf_t *out) {{"
    )
    .unwrap();
    if m.args.is_empty() {
        writeln!(out, "    (void)m; (void)out;").unwrap();
        writeln!(out, "    return WW_OK;").unwrap();
    } else {
        writeln!(out, "    int rc;").unwrap();
        writeln!(out, "    (void)m;").unwrap();
        for a in &m.args {
            let field = c_field_name(&a.name);
            let call = encode_call_for(&a.ty, &field);
            writeln!(
                out,
                "    if ((rc = {call}(out, {arg}))) return rc;",
                arg = encode_arg_expr(&a.ty, &field)
            )
            .unwrap();
        }
        writeln!(out, "    return WW_OK;").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ---- decode ----
    writeln!(
        out,
        "int {fn_prefix}_decode(const uint8_t *buf, size_t len, {type_name} *out) {{"
    )
    .unwrap();
    writeln!(out, "    memset(out, 0, sizeof(*out));").unwrap();
    writeln!(out, "    ww_rd_t r = {{ buf, 0, len }};").unwrap();
    if m.args.is_empty() {
        writeln!(out, "    (void)r;").unwrap();
    } else {
        writeln!(out, "    int rc;").unwrap();
        for a in &m.args {
            let field = c_field_name(&a.name);
            let call = decode_call_for(&a.ty);
            writeln!(out, "    if ((rc = {call}(&r, &out->{field}))) goto fail;").unwrap();
        }
    }
    writeln!(out, "    if (r.pos != r.len) {{").unwrap();
    if !m.args.is_empty() {
        writeln!(out, "        int rc2 = WW_ERR_TRAILING;").unwrap();
        writeln!(out, "        (void)rc2;").unwrap();
        writeln!(out, "        {fn_prefix}_free(out);").unwrap();
    } else {
        writeln!(
            out,
            "        /* empty message; no allocations to release */"
        )
        .unwrap();
    }
    writeln!(out, "        return WW_ERR_TRAILING;").unwrap();
    writeln!(out, "    }}").unwrap();
    writeln!(out, "    return WW_OK;").unwrap();
    if !m.args.is_empty() {
        writeln!(out, "fail:").unwrap();
        writeln!(out, "    {fn_prefix}_free(out);").unwrap();
        writeln!(out, "    return rc;").unwrap();
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ---- free ----
    writeln!(out, "void {fn_prefix}_free({type_name} *m) {{").unwrap();
    let owned: Vec<_> = m.args.iter().filter(|a| ty_owns_heap(&a.ty)).collect();
    if owned.is_empty() {
        writeln!(out, "    (void)m;").unwrap();
    } else {
        for a in &owned {
            let field = c_field_name(&a.name);
            writeln!(out, "    {}", free_stmt_for(&a.ty, &field)).unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // ---- expected_fds ----
    writeln!(
        out,
        "uint32_t {fn_prefix}_expected_fds(const {type_name} *m) {{"
    )
    .unwrap();
    match &m.fds {
        FdSpec::None => {
            writeln!(out, "    (void)m;").unwrap();
            writeln!(out, "    return 0;").unwrap();
        }
        FdSpec::Fixed(n) => {
            writeln!(out, "    (void)m;").unwrap();
            writeln!(out, "    return {n};").unwrap();
        }
        FdSpec::Product(fields) => {
            let expr = fields
                .iter()
                .map(|path| {
                    let field_path = path
                        .split('.')
                        .map(c_field_name)
                        .collect::<Vec<_>>()
                        .join(".");
                    format!("(uint64_t)m->{field_path}")
                })
                .collect::<Vec<_>>()
                .join(" * ");
            writeln!(out, "    return (uint32_t)({expr});").unwrap();
        }
    }
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();
}

fn encode_call_for(ty: &ArgType, _field: &str) -> String {
    match ty {
        ArgType::Bool => "w_bool".into(),
        ArgType::U32 => "w_u32".into(),
        ArgType::I32 => "w_i32".into(),
        ArgType::U64 => "w_u64".into(),
        ArgType::I64 => "w_i64".into(),
        ArgType::F32 => "w_f32".into(),
        ArgType::F64 => "w_f64".into(),
        ArgType::String => "w_string".into(),
        ArgType::Rect => "w_rect".into(),
        ArgType::KvList => "w_kv_list".into(),
        ArgType::Array(elem) => match **elem {
            ArgType::U32 => "w_array_u32".into(),
            ArgType::I32 => "w_array_i32".into(),
            ArgType::U64 => "w_array_u64".into(),
            ArgType::I64 => "w_array_i64".into(),
            ArgType::F32 => "w_array_f32".into(),
            ArgType::F64 => "w_array_f64".into(),
            ArgType::String => "w_array_string".into(),
            _ => panic!("bad array"),
        },
        ArgType::Named(name) => format!("w_{name}"),
        ArgType::Enum(name) => format!("w_{name}"),
    }
}

fn encode_arg_expr(ty: &ArgType, field: &str) -> String {
    match ty {
        ArgType::Bool
        | ArgType::U32
        | ArgType::I32
        | ArgType::U64
        | ArgType::I64
        | ArgType::F32
        | ArgType::F64
        | ArgType::Enum(_) => {
            format!("m->{field}")
        }
        ArgType::String => format!("m->{field}"),
        ArgType::Rect | ArgType::KvList | ArgType::Array(_) | ArgType::Named(_) => {
            format!("&m->{field}")
        }
    }
}

fn decode_call_for(ty: &ArgType) -> String {
    match ty {
        ArgType::Bool => "rd_bool".into(),
        ArgType::U32 => "rd_u32".into(),
        ArgType::I32 => "rd_i32".into(),
        ArgType::U64 => "rd_u64".into(),
        ArgType::I64 => "rd_i64".into(),
        ArgType::F32 => "rd_f32".into(),
        ArgType::F64 => "rd_f64".into(),
        ArgType::String => "rd_string".into(),
        ArgType::Rect => "rd_rect".into(),
        ArgType::KvList => "rd_kv_list".into(),
        ArgType::Array(elem) => match **elem {
            ArgType::U32 => "rd_array_u32".into(),
            ArgType::I32 => "rd_array_i32".into(),
            ArgType::U64 => "rd_array_u64".into(),
            ArgType::I64 => "rd_array_i64".into(),
            ArgType::F32 => "rd_array_f32".into(),
            ArgType::F64 => "rd_array_f64".into(),
            ArgType::String => "rd_array_string".into(),
            _ => panic!("bad array"),
        },
        ArgType::Named(name) => format!("rd_{name}"),
        ArgType::Enum(name) => format!("rd_{name}"),
    }
}

fn ty_owns_heap(ty: &ArgType) -> bool {
    matches!(
        ty,
        ArgType::String | ArgType::KvList | ArgType::Array(_) | ArgType::Named(_)
    )
}

fn free_stmt_for(ty: &ArgType, field: &str) -> String {
    free_stmt_for_base(ty, "m", field)
}

fn free_stmt_for_base(ty: &ArgType, base: &str, field: &str) -> String {
    match ty {
        ArgType::String => format!("free({base}->{field}); {base}->{field} = NULL;"),
        ArgType::KvList => format!("free_kv_list(&{base}->{field});"),
        ArgType::Array(elem) => match **elem {
            ArgType::String => format!("free_array_string(&{base}->{field});"),
            _ => format!(
                "free({base}->{field}.data); {base}->{field}.data = NULL; {base}->{field}.count = 0;"
            ),
        },
        ArgType::Named(name) => format!("free_{name}(&{base}->{field});"),
        _ => format!("/* {field}: no heap */"),
    }
}

// ---------------------------------------------------------------------------
// Type & name mapping

fn message_type_name(m: &Message, kind: MsgKind) -> String {
    format!("{}{}_t", kind.prefix(), m.name)
}

fn c_type(ty: &ArgType) -> String {
    match ty {
        ArgType::Bool => "bool".into(),
        ArgType::U32 => "uint32_t".into(),
        ArgType::I32 => "int32_t".into(),
        ArgType::U64 => "uint64_t".into(),
        ArgType::I64 => "int64_t".into(),
        ArgType::F32 => "float".into(),
        ArgType::F64 => "double".into(),
        ArgType::String => "char *".into(),
        ArgType::Rect => "ww_rect_t".into(),
        ArgType::KvList => "ww_kv_list_t".into(),
        ArgType::Array(elem) => match **elem {
            ArgType::U32 => "ww_array_u32_t".into(),
            ArgType::I32 => "ww_array_i32_t".into(),
            ArgType::U64 => "ww_array_u64_t".into(),
            ArgType::I64 => "ww_array_i64_t".into(),
            ArgType::F32 => "ww_array_f32_t".into(),
            ArgType::F64 => "ww_array_f64_t".into(),
            ArgType::String => "ww_array_string_t".into(),
            _ => panic!("unsupported array element in C codegen"),
        },
        ArgType::Named(name) => named_c_type(name),
        ArgType::Enum(name) => named_c_type(name),
    }
}

fn named_c_type(name: &str) -> String {
    format!("waywallen_{name}_t")
}

/// C reserved identifiers that could collide with protocol arg names.
/// Prefix with `m_` to disambiguate.
fn c_field_name(raw: &str) -> String {
    match raw {
        "default" | "auto" | "register" | "restrict" | "return" | "static" | "struct" | "union"
        | "class" | "new" | "delete" => format!("m_{raw}"),
        _ => raw.to_string(),
    }
}

// ---------------------------------------------------------------------------
// Tests

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    fn parse(src: &str) -> Protocol {
        parser::parse_protocol(src).unwrap()
    }

    #[test]
    fn header_contains_protocol_macros() {
        let p = parse(
            r#"<protocol name="foo" version="1">
                <request name="hello" opcode="1">
                    <arg name="x" type="u32"/>
                </request>
            </protocol>"#,
        );
        let h = emit_header(&p);
        assert!(h.contains("#define WW_PROTOCOL_NAME    \"foo-v1\""));
        assert!(h.contains("#define WW_PROTOCOL_VERSION 1"));
        assert!(h.contains("WW_REQ_HELLO = 1"));
        assert!(h.contains("typedef struct ww_req_hello"));
        assert!(h.contains("ww_req_hello_encode"));
        assert!(h.contains("ww_req_hello_decode"));
        assert!(h.contains("ww_req_hello_free"));
        assert!(h.contains("ww_req_hello_expected_fds"));
    }

    #[test]
    fn header_events_render() {
        let p = parse(
            r#"<protocol name="t" version="1">
                <event name="welcome" opcode="1">
                    <arg name="server_version" type="string"/>
                    <arg name="features" type="array" element="string"/>
                </event>
            </protocol>"#,
        );
        let h = emit_header(&p);
        assert!(h.contains("WW_EVT_WELCOME = 1"));
        assert!(h.contains("char *server_version"));
        assert!(h.contains("ww_array_string_t features"));
    }

    #[test]
    fn header_rect_type_present() {
        let p = parse(
            r#"<protocol name="t" version="1">
                <event name="cfg" opcode="1">
                    <arg name="r" type="rect"/>
                </event>
            </protocol>"#,
        );
        let h = emit_header(&p);
        assert!(h.contains("typedef struct ww_rect"));
        assert!(h.contains("ww_rect_t r;"));
    }

    #[test]
    fn named_struct_types_are_shared_by_messages() {
        let p = parse(
            r#"<protocol name="t" version="1">
                <struct name="config">
                    <field name="enabled" type="bool"/>
                </struct>
                <event name="configured" opcode="1">
                    <arg name="config" type="config"/>
                </event>
            </protocol>"#,
        );
        let h = emit_header(&p);
        assert!(h.contains("typedef struct waywallen_config"));
        assert!(h.contains("bool enabled;"));
        assert!(h.contains("waywallen_config_t config;"));
        assert!(h.contains("void waywallen_config_free(waywallen_config_t *value);"));

        let source = emit_source(&p);
        assert!(source.contains("void waywallen_config_free(waywallen_config_t *value)"));

        let types = emit_types_header(&p);
        assert!(types.contains("waywallen_config_t"));
        assert!(!types.contains("ww_evt_configured_t"));
    }

    #[test]
    fn nested_struct_fields_drive_fd_count() {
        let p = parse(
            r#"<protocol name="t" version="1">
                <struct name="pool">
                    <field name="count" type="u32"/>
                    <field name="planes" type="u32"/>
                </struct>
                <event name="bind" opcode="1">
                    <arg name="pool" type="pool"/>
                    <fds count_expr="pool.count * pool.planes"/>
                </event>
            </protocol>"#,
        );
        let source = emit_source(&p);
        assert!(source.contains("(uint64_t)m->pool.count * (uint64_t)m->pool.planes"));
    }
}
